baseURL = "https://themerchantguide.com"
languageCode = "en-us"
title = "TheMerchantGuide"
description = "Find the perfect payment processor for your business"

[params]
  author = "TheMerchantGuide"
  description = "The smart way for small retailers, e-commerce startups, and regional businesses to find payment processors that actually fit their needs and budget"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 20
  
  [[menu.main]]
    name = "Podcast"
    url = "/podcasts/"
    weight = 30
  
  [[menu.main]]
    name = "Resources"
    url = "/resources/"
    weight = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
